Add Windows installer
subdgtl/HURBAN-Selector pull request #111
Opened 2020-01-05 16:35 UTC by ondrowan

To try this, follow the steps from main README / README of installer. Most of the files are just copied from [innodependencyinstaller](https://github.com/domgho/innodependencyinstaller). Redistributables are contained in installer itself. I tried it on my computer and it installed everything properly, but I'd prefer if we tired it also on some clean installation of Windows to make sure everything works as intended. The only thing that is missing for now is icon, but that can be added later.

2020-01-11 12:27 UTC, yanchith reviewed
Seems to work on my computer. Unfortunately my computer is not clean, so we don't know for sure 🙁, we'll have to wait until I reinstall or we find a clean computer somewhere.

I didn't spend that much time on the code, but I do have a couple of general questions:

- Is `installer/Output/HURBAN Selector-1.0.exe` supposed to be checked into version control? Seems like you just changed the target directory and forgot to delete this.
- Can this be extended to add the app icon later?
- Can this be extended to create shortcuts later?
- Can this be extended to set windows file associations later?

2020-01-11 16:32 UTC, ondrowan commented
@yanchith I've removed that installer that was in VC by accident. Also added a possibility to create desktop and Start Menu shortcut. As for icons and file associations: yes to both.

2020-01-16 13:35 UTC, yanchith commented
@ondrowan as we discussed in person, please add a dummy icon now that we can later replace with official one.

2020-01-16 20:34 UTC, janper commented
@ondrowan, I was asked to ask here: https://github.com/subdgtl/HURBAN-Selector/pull/114#issuecomment-575333339

2020-01-18 20:29 UTC, ondrowan commented
@janper Yes, it is in Start menu and it is possible to add link to logs folder there.

2020-01-18 21:07 UTC, janper commented
> @janper Yes, it is in Start menu and it is possible to add link to logs folder there.

let's do it then, please

2020-01-18 23:01 UTC, ondrowan commented
Done and done. Adding an icon to binary requires a manual step, but it's much less awkward than alternatives I found. The only place where I couldn't get the icon to show is the upper left corner of the application window, but I'll investigate it later.

2020-01-26 01:03 UTC, janper commented
Yeah, please, try to resolve also the issue with the window icon. Would be weird not having it.

2020-02-02 20:38 UTC, ondrowan commented
@janper It's there. For now, it builds with icon even in debug mode. I'd like to keep it that way just to be able to spot if something's wrong right away.

2020-02-07 15:46 UTC, yanchith commented on README.md
> +- `cargo build --release`,
This is now missing the `--features dist`

2020-02-07 15:52 UTC, yanchith commented on README.md
> +- `cargo build --release`,
Hmm, maybe this should just link to the installer readme, so we don't have to double-maintain it? They are already out of sync.

2020-02-07 16:01 UTC, yanchith commented
@ondrowan I think this is almost good to go once you resolve my comments regarding the readme and fix merge conflicts. @janper do you require anything else here?

2020-02-09 09:53 UTC, yanchith submitted a review, later dismissed

2020-02-10 09:12 UTC, janper commented
I'm indifferent to this.

2020-02-10 09:43 UTC, janper requested changes
I gave it a try. 
if I understand correctly, you first need to build the binary, then add the icon, then compile the installer? If so, please rewrite the readme accordingly.

Also (maybe some sort of my fault) but I'm unable to `cargo build --release --features dist`. Resulting with the following error:
```
Compiling hurban_selector v0.1.0 (C:\Users\daroi\Documents\HURBAN-Selector)
error[E0308]: mismatched types
  --> src\logger.rs:78:9
   |
77 |     let path = match dirs::data_local_dir() { 
   |                      ---------------------- this match expression has type `std::option::Option<std::path::PathBuf>`
78 |         Ok(appdata_local) => Path::new(&appdata_local).join("HURBAN Selector/Logs"),
   |         ^^^^^^^^^^^^^^^^^ expected enum `std::option::Option`, found enum `std::result::Result`  
   |
   = note: expected type `std::option::Option<std::path::PathBuf>`
              found type `std::result::Result<_, _>`

error[E0308]: mismatched types
  --> src\logger.rs:79:9
   |
77 |     let path = match dirs::data_local_dir() { 
   |                      ---------------------- this match expression has type `std::option::Option<std::path::PathBuf>`
78 |         Ok(appdata_local) => Path::new(&appdata_local).join("HURBAN Selector/Logs"),
79 |         Err(_) => return base_logger,
   |         ^^^^^^ expected enum `std::option::Option`, found enum `std::result::Result`
   |
   = note: expected type `std::option::Option<std::path::PathBuf>`
              found type `std::result::Result<_, _>`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `hurban_selector`.        

To learn more, run the command again with --verbose.
```

2020-02-10 09:58 UTC, janper commented
Also I'd appreciate a link to rcedit binaries. I tried to build it from source but failed.
![image](https://user-images.githubusercontent.com/3333537/74139755-387c6000-4bf4-11ea-8a3c-57a9c8e70456.png)

2020-02-10 10:03 UTC, yanchith commented
> Also I'd appreciate a link to rcedit binaries. I tried to build it from source but failed.

There is a link in the link Ondro added to the readme. But I can point to it directly. You shouldn't build it from source.

2020-02-10 10:13 UTC, yanchith commented
@janper please try again. I fixed the issues.

2020-02-10 12:11 UTC, janper approved these changes

2020-02-10 12:14 UTC, merged

2020-02-10 12:14 UTC, janper commented
It's acceptable now. Two notes though (decide if relevant or not):
1. I didn't realize the file icon and the window icon may differ. I used a different icon for the exe accidentally. A more detailed description in the readme would be nice.
2. I know this is may be tricky but I'd suggest spending a couple of minutes searching to see if it is easy to fix: I don't mind the warning itself but the publisher should be "Subdigital"
![image](https://user-images.githubusercontent.com/3333537/74149092-3cfe4400-4c07-11ea-985b-f221f453420f.png)

2020-02-10 12:20 UTC, yanchith commented
Damn. I merged before seeing your comment. Okay, I'll push a more detailed description of the icons to master in the evening. Do we want to use different icons?

I'll investigate if we can set the piblisher.