Add Simplex noise UI operation
subdgtl/HURBAN-Selector pull request #164
Opened 2020-03-20 16:42 UTC by janper

![image](https://user-images.githubusercontent.com/3333537/77185629-0226e000-6ad2-11ea-8746-2411d9ad5202.png)

2020-03-27 09:54 UTC, yanchith requested changes
Noise! See inline comments. Mostly the PR is a bit out of date, but nothing major.

2020-03-27 09:54 UTC, yanchith commented on src/interpreter_funcs/mod.rs
> +pub const FUNC_ID_VOXEL_NOISE: FuncIdent = FuncIdent(8004);
Will need to resolve conflicts with master here

2020-03-27 09:54 UTC, yanchith commented on src/mesh/voxel_cloud.rs
> +            let noise_scale_f64 = noise_scale as f64;
`f64::from`

2020-03-27 09:54 UTC, yanchith commented on src/mesh/voxel_cloud.rs
> +                time_offset as f64,
`f64::from` everywhere

2020-03-27 09:54 UTC, yanchith commented on src/interpreter_funcs/voxel_noise.rs
> +                description: "Size of a single cell in the regular three-dimensional voxel grid.\n\
Two newlines here?

2020-03-27 09:54 UTC, yanchith commented on src/interpreter_funcs/voxel_noise.rs
> +                heavier geometry that significantly affect performance. Too high values produce \
affects

2020-03-27 09:54 UTC, yanchith commented on src/interpreter_funcs/voxel_noise.rs
> +                    min_value: Some(f32::MIN_POSITIVE),
Why not zero? For 4D noise it is a dimension like any other.

2020-03-27 09:54 UTC, yanchith commented on src/interpreter_funcs/voxel_noise.rs
> +            .any(|dimension| approx::relative_eq!(*dimension, 0.0))
Account for negative values

2020-03-27 09:54 UTC, yanchith commented on src/interpreter_funcs/voxel_noise.rs
> +            return Err(error);
I believe this has been extracted somewhere already?

2020-03-27 09:54 UTC, yanchith commented on src/interpreter_funcs/voxel_noise.rs
> +        match scalar_field.to_mesh(&meshing_range) {
We are missing marching cubes here.

2020-03-29 08:32 UTC, janper commented
ready for another review

2020-03-29 11:48 UTC, yanchith approved these changes

2020-03-29 11:50 UTC, merged