Find orphans
subdgtl/HURBAN-Selector pull request #29
Opened 2019-09-28 19:37 UTC by janper

Adding a standalone function `has_no_orphans` into `Geometry` where it should semantically belong.

2019-09-29 20:41 UTC, ondrowan requested changes
There's couple of things I'd like to point out:

* In both constructors of `Geometry` there's a `FIXME: orphan removal`. Shouldn't this be part of construction of geometry?
* Whatever happens with this, it's a good candidate for a couple of unit tests.

2019-09-30 15:55 UTC, janper commented
> There's couple of things I'd like to point out:
> 
> * In both constructors of `Geometry` there's a `FIXME: orphan removal`. Shouldn't this be part of construction of geometry?

I'm on it but first I'm putting together analytic tools, then fixes

> * Whatever happens with this, it's a good candidate for a couple of unit tests.

I can only imagine tests using sample data. And THB, I'm trying to avoid that work.

2019-09-30 17:22 UTC, yanchith commented
>> Whatever happens with this, it's a good candidate for a couple of unit tests.

> I can only imagine tests using sample data. And THB, I'm trying to avoid that work.

I understand geometric ops are hard to test in general, but this one actually is really easy to create test data for. Would be a shame not to do it 😉

2019-10-03 21:24 UTC, janper commented
requested tests done, ready for merging

2019-10-04 08:31 UTC, yanchith commented on src/geometry.rs
> +    fn test_orphan_vertex_detection() {
For future reference, it is better to cover one test case with one test function for better granularity. If this test fails, one does not know exactly why immediately and has to do more investigation to find out. Same for: `test_orphan_normal_detection`

2019-10-04 08:34 UTC, yanchith commented
Looks acceptable to me. @ondrowan, if you agree, I'll squash and merge. Or do you want to learn how to squash commits, @janper ? 😸

2019-10-04 08:54 UTC, ondrowan commented
I'd still split that test case and use a bit more proper naming of test methods: `test_{name_of_tested_method}_{what_is_being_tested}`. Eg. `test_has_no_orphan_vertices_returns_true_if_there_are_some` and `test_has_no_orphan_vertices_returns_false_if_there_are_none`. Or something along that way.

2019-10-05 08:13 UTC, janper commented
requested changes done

2019-10-05 10:32 UTC, ondrowan approved these changes

2019-10-05 10:33 UTC, ondrowan commented
@janper Squash the commits and 🚢 🇮🇹 !

2019-10-05 18:03 UTC, merged