Stop Laplacian smoothing with anchors when the geometry becomes stable
subdgtl/HURBAN-Selector pull request #54
Opened 2019-10-25 12:44 UTC by janper

The Laplacian smoothing with anchors can be used to paramterize a mesh patch into a flat disc. Once the edge loop is transformed into the circumference of the target disc, the iterative algorithm of Laplacian smoothing is applied until the mesh reaches a stable spatial configuration.

This function will be later used in more complex operations, therefore it's not exposed as a distinct operation.

2019-10-25 19:06 UTC, ondrowan requested changes

2019-10-25 19:06 UTC, ondrowan commented on src/lib.rs
> +extern crate approx;
There's no need to do this. Just prefix `relative_eq` with `approx::` and you won't need to import anything.

2019-10-25 19:06 UTC, ondrowan commented on src/mesh_smoothing.rs
> +    println!("Stop when stable: {}", stop_when_stable);
This should be most likely removed.

2019-10-25 19:06 UTC, ondrowan commented on src/mesh_smoothing.rs
>                      average_position += geometry_vertices[cast_usize(*neighbor_index)].coords;
Not part of this PR, but I found that closure in condition can be simiplified to `|i| i != current_vertex_index` since `current_vertex_index` is already `u32`. `cast_u32` import won't be needed as well.

2019-10-25 19:06 UTC, ondrowan commented on src/mesh_smoothing.rs
> +                    stable &= relative_eq!(
Does this `&` have any special meaning here? Is there a case when `stable` would be `true` and `false` from `relative_eq` would invalidate it?

2019-10-25 20:08 UTC, janper commented on src/mesh_smoothing.rs
> +    println!("Stop when stable: {}", stop_when_stable);
yup, that's just forgotten

2019-10-25 20:10 UTC, janper commented on src/mesh_smoothing.rs
> +                    stable &= relative_eq!(
sure, if some vertices are already stable and some are not, then the iterations need to continue

2019-10-28 14:37 UTC, ondrowan submitted a review, later dismissed
It looks good to me, but let's wait for @yanchith to review this as well.

2019-10-29 10:28 UTC, yanchith submitted a review, later dismissed
❤️

2019-10-29 13:25 UTC, janper commented
Now I think maybe i should refactor it so that the operation itself runs the logic iteratively. It would be then possible to test the function properly plus in the future when we have the iterative operations with feedback, there will be no need to refactor this. Also the log will be nicer. Wouldn't you mind one more refactor?

2019-10-29 13:53 UTC, yanchith commented
@janper 

> Wouldn't you mind one more refactor?

Have no strong opinion on this, but the default for me is to do work later, once we really require it.

2019-10-29 17:24 UTC, yanchith requested changes
Nice refactor 👍  but please address inline comments.

2019-10-29 17:24 UTC, yanchith commented on src/interpreter_funcs.rs
> +            cast_u32(cmp::min(255, iterations)),
This is already a `u32`, no need to cast.

2019-10-29 17:24 UTC, yanchith commented on src/mesh_smoothing.rs
> +pub fn laplacian_smoothing_with_anchors_full(
I think there's now way too many of the `laplacian_smoothing_*` functions. Let's keep just the most generic one (and call it just `laplacian_smoothing`) and use that everywhere. Also make sure its docs are up to date and correctly formatted. Let's keep the tests for the various variants, just inline the function with concrete parameters set there.

2019-10-29 17:24 UTC, yanchith commented on src/mesh_smoothing.rs
> +        return (geometry.clone(), 0, stop_when_stable);
Consistency nit: I think `false` is more correct than `stop_when_stable` here. The changes could not have stabilized if there were no changes.

2019-10-30 07:56 UTC, yanchith commented on src/mesh_smoothing.rs
> +pub fn laplacian_smoothing_with_anchors_full(
@janper Almost done, but you still forgot the rename to `laplacian_smoothing`

2019-10-30 12:02 UTC, yanchith approved these changes

2019-10-30 12:47 UTC, merged