Implementation of UI wrapper
subdgtl/HURBAN-Selector pull request #7
Opened 2019-08-19 11:32 UTC by ondrowan

This is a convenience wrapper around imgui and all of its orchestration. Its practicality can be questioned, but it's the first iteration and I find it to be friendlier than the barebones alternative. All options are also hardcoded, which I (partly) don't expect to stay that way in the future.

2019-08-19 15:21 UTC, yanchith requested changes
Nice job!

Except for `ui_capture_{keyboard,mouse}` and the vulkan validation layer errors, all my comments are minor and easily fixable.

Note: either the FPS computation is broken, or vsync doesn't work, got 2000fps on debug builds and over 9000 on release builds 😄
Would explain the GPU usage.

2019-08-19 15:21 UTC, yanchith commented on src/main.rs
> +            let (ui_captured_keyboard, ui_captured_mouse) = ui.process_event(&event);
I think the use of `ui_captured_{keyboard,mouse}` here is incorrect. One can know their true values only after imgui has seen all the input events for the current frame.... What needs to happen is:

1) feed all the events to imgui
2) get `ui_captured_{keyboard,mouse}` from imgui
3) feed all the events to our input manager, together with the flags

This is a bit unfortunate, because it forces us to buffer events. Pseudocode:

```
input_buffer = []
for ev in poll_events():
    input_buffer.push(ev);
    ui.process_event(ev);

(ui_captured_kbd, ui_captured_mouse) = ui.captured_keyboard(), ui.captured_mouse();
for ev in input_buffer:
    input_manager.process_event(ev, ui_captured_kbd, ui_captured_mouse);
```

Definitely not ideal, but will do as a workaround for now. We can clean this up later, but I am not sure. For more context, see: https://github.com/Gekkio/imgui-rs/issues/128

2019-08-19 15:21 UTC, yanchith commented on src/ui.rs
> +    pub fn update_delta_time(&mut self, delta: Instant) -> Instant {
It seems very weird that imgui should be updating our time delta when we do it already... This should be just `set_delta_time()`.

The imgui implementation is this:

```rust
pub fn update_delta_time(&mut self, previous: Instant) -> Instant {
        let now = Instant::now();
        let delta = now - previous;
        let delta_s = delta.as_secs() as f32 + delta.subsec_nanos() as f32 / 1_000_000_000.0;
        if delta_s > 0.0 {
            self.delta_time = delta_s;
        } else {
            self.delta_time = f32::MIN_POSITIVE;
        }
        self.delta_time = delta_s;
        now
    }
```

We can steal the "duration to float" conversion from its implementation and use it here to set time delta on IO.

Float duration (https://github.com/rust-lang/rust/issues/54361) would be helpful but they will only be stabilized in 1.38... we can add a FIXME to use them 😂

2019-08-19 15:21 UTC, yanchith commented on src/shaders/imgui.vert
> +    vec2 u_Translate;
I meanwhile started naming the variables and functions in shaders in `snake_case` only, e.g: `u_translate`. We can pick either, but if you want this one, please change the existing shaders to the same convention.

2019-08-19 15:21 UTC, yanchith commented on src/shaders/imgui.frag
> +layout(location = 0) in vec2 v_UV;
Would name this `tex_coords`  instead of `uv` to be consistent with the other shader

2019-08-19 15:21 UTC, yanchith commented on src/shaders/imgui.frag
> +    o_Target = v_Color * texture(sampler2D(u_Texture, u_Sampler), v_UV);
Would name this `o_color` instead of `o_target` to be consistent with the other shader... `target` is not a bad name too tho, so If you like it better, just rename `o_color` in the other fragment shader to `o_target`

2019-08-19 15:21 UTC, yanchith commented on src/imgui_renderer.rs
> +        let vs_spv = include_bytes!(concat!(env!("OUT_DIR"), "/shaders/imgui.vert.spv"));
Could use the `include_shader!` macro defined in the viewport renderer. You will need to move it to a separate module though because of how `#[macro_use]` works.

2019-08-19 15:21 UTC, yanchith commented on src/imgui_renderer.rs
> +fn upload_buffer_immediate(device: &mut wgpu::Device, buffer: &wgpu::Buffer, data: &[f32]) {
Instead of `data: &[f32]` I would pass a `repr(C)` struct named `TransformUniforms` or similar, symmetric to what viewport renderer does with `GlobalMatrixUniforms` struct. This upload then becomes much less error-prone. Have a look at `upload_global_matrix_buffer`. I learned this nice trick reading the `wgpu-rs` examples.

This function won't really be general-purpose anyway, so it may as well expect a concrete struct with correct memory layout.

(I know, I know... I learned a lot about things since writing the base code you were starting with, sorry for giving you bad starting code)

2019-08-19 15:21 UTC, yanchith commented on src/imgui_renderer.rs
> +const UNIFORM_BUFFER_SIZE: u64 = 16;
I would replace this constant at the use sites with much more meaningful: `wgpu_size_of::<T>()`. You can find the function in the viewport renderer and extract it (or just copy it for now - we will have to refactor later anyway).

The `T` would be the `TransformationUniforms` `repr(C)` struct.

2019-08-19 15:21 UTC, yanchith commented on src/imgui_renderer.rs
> +        data: &[u8],
Let's assert `data.len() % 4 == 0` here. We can later create a wrapper (e.g.: `Rgba32Texture` for the buffer) ensuring this holds.

2019-08-19 15:21 UTC, yanchith commented on src/imgui_renderer.rs
> +            index_format: wgpu::IndexFormat::Uint16, // FIXME(yanchith): may need 32bit indices!
Ugh... Let's let this slide for now, but we shouldn't forget about it. If UI suddenly breaks when it gets big, remember this :))

2019-08-19 15:21 UTC, yanchith commented on src/imgui_renderer.rs
> +                stride: u64::try_from(Self::DRAW_VERT_SIZE).unwrap(),
Let's change this to `wgpu_size_of::<imgui::DrawVert>()` and remove the associated const.

2019-08-19 15:21 UTC, yanchith commented on src/main.rs
> +        time = ui.update_delta_time(time);
See my other comment about `ui.update_delta_time()`... basically we probably don't want to be using this imgui helper as we are already computing the same thing ourselves (see top of the application loop).

I think this should  be: `ui.set_delta_time(duration_last_frame);` with the duration being internally converted to a float inside the method.

2019-08-19 15:21 UTC, yanchith commented on src/ui.rs
> +    window: &'w wgpu::winit::Window,
`winit::Window`?

2019-08-19 15:21 UTC, yanchith commented on src/ui.rs
> +    pub fn create<F>(&mut self, callback: F) -> &imgui::DrawData
`create()`? Isn't `draw()` or something more accurate?

2019-08-19 15:21 UTC, yanchith commented on src/imgui_renderer.rs
> +            usage: wgpu::TextureUsage::SAMPLED,
You are missing the `TextureUsage::TRANSFER_DST` bit, VK validation layers complain:

```
[2019-08-19T14:12:27Z ERROR gfx_backend_vulkan]
VALIDATION [VUID-vkCmdCopyBufferToImage-dstImage-00177 (0)] : Invalid usage flag for VkImage 0x41[] used by vkCmdCopyBufferToImage(). In this case, VkImage should have VK_IMAGE_USAGE_TRANSFER_DST_BIT set during creation. The Vulkan spec states: dstImage must have been created with VK_IMAGE_USAGE_TRANSFER_DST_BIT usage flag (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkCmdCopyBufferToImage-dstImage-00177)
object info: (type: IMAGE, hndl: 65)

[2019-08-19T14:12:27Z ERROR gfx_backend_vulkan]
VALIDATION [VUID-VkImageMemoryBarrier-oldLayout-01213 (0)] : vkCmdPipelineBarrier(): Image barrier 0x000000832B8FC5C8 new Layout=VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL is not compatible with VkImage 0x41[] usage flags 0x4. The Vulkan spec states: If either oldLayout or newLayout is VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL then image must have been created with VK_IMAGE_USAGE_TRANSFER_DST_BIT set (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkImageMemoryBarrier-oldLayout-01213)
object info: (type: IMAGE, hndl: 65)

[2019-08-19T14:12:27Z ERROR gfx_backend_vulkan]
VALIDATION [VUID-VkImageMemoryBarrier-oldLayout-01213 (0)] : vkCmdPipelineBarrier(): Image barrier 0x000000832B8FCD48 old Layout=VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL is not compatible with VkImage 0x41[] usage flags 0x4. The Vulkan spec states: If either oldLayout or newLayout is VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL then image must have been created with VK_IMAGE_USAGE_TRANSFER_DST_BIT set (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkImageMemoryBarrier-oldLayout-01213)
object info: (type: IMAGE, hndl: 65)
```

2019-08-19 15:21 UTC, yanchith commented on src/imgui_renderer.rs
> +            usage: wgpu::TextureUsage::SAMPLED,
This is missing the `TextureUsage::TRANSFER_DST` bit

2019-08-19 15:21 UTC, yanchith commented on src/imgui_renderer.rs
> +use imgui::internal::RawWrapper;
Is this unused?

2019-08-21 13:38 UTC, ondrowan commented on src/imgui_renderer.rs
> +use imgui::internal::RawWrapper;
There's `.raw()` call that needs it.

2019-08-21 16:11 UTC, yanchith commented on src/imgui_renderer.rs
> +                stride: u64::try_from(wgpu_size_of::<imgui::DrawVert>())
Redundant `try_from`, `wgpu_size_of` already returns `u64` (type aliased as `wgpu::BufferAddress`)

2019-08-21 16:17 UTC, yanchith commented on src/main.rs
> +            let duration_last_frame_s = duration_last_frame.as_secs() as f32
Can leave a FIXME here to change to https://doc.rust-lang.org/std/time/struct.Duration.html#method.as_secs_f32 when it stabilizes in 1.38.0

2019-08-21 16:23 UTC, yanchith approved these changes
Beautiful 👍

2019-08-21 16:37 UTC, merged